[package]
name = "actix"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
mongodb = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-web = "4"
serde_with = "1.11"
log = "0.4"
env_logger = "0.9"