version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017
      MONGO_DB: mydb

  mongo:
    image: mongo:4.4
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.stats()"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--dbpath", "/data/db", "--bind_ip", "0.0.0.0"]

volumes:
  mongo-data: