
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017
      MONGO_DB: mydb

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - ./logs:/var/log/mongodb
    command: ["mongod", "--config", "/etc/mongod.conf"]

volumes:
  mongo-data:
  logs: